Drawer component and Tanstack Routing
Julianna-Venter/React-Project-Github pull request #4
Opened 2024-03-14 16:48 UTC by Julianna-Venter

Moved the nav bar into drawer component and added routing via drawer and buttons. This is still hard coded, purely UI (not web responsive yet)

2024-03-14 18:52 UTC, Hugovs2000 requested changes
Just the comments about how you are destructing your props and questionable underground browser fighting 👀

2024-03-14 18:52 UTC, Hugovs2000 commented on src/Navigation/Drawer.tsx
> +const Drawer: React.FC<DrawerProps> = ({ username }) => {
I think you can do  `const Drawer: React.FC<DrawerProps> = ({ username }:{username:string}) => {...}` and then you do not neet the interface.

2024-03-14 18:52 UTC, Hugovs2000 commented on src/commonComponents/BackgroundAssets.tsx
> +      <div className="w-[18.75rem] h-[9.375rem] border-solid border-12 border-secondary_orange absolute rounded-badge -z-10 left-[6rem] top-[-8rem] rotate-45 flex-0"></div>
Kinda sketch, looks like you are fighting the browser.

2024-03-15 06:25 UTC, yanevdw commented on src/Navigation/Drawer.tsx
> +                className="w-4 h-4 text-ligher_text"
On ```Line 55```, I assume this should be "lighter"?

2024-03-15 06:26 UTC, yanevdw commented on src/userForm/UserForm.tsx
> +            <h2 className="text-ligher_text text-sm lg:text-base">
On ```Line 30```: Same typo here.

2024-03-15 06:37 UTC, yanevdw requested changes
- As far as the drawer and routing is concerned, nicely done.
- Take a look at the comments.
-  Please take a look at your ```tailwind.config.js``` file, specifically your naming conventions for the custom colours. The naming convention should be kebab-case.
- Also just a suggestion on the naming of the custom text colours, just name the colour insted of ```text-colour```.

2024-03-15 07:29 UTC, Julianna-Venter commented
> * As far as the drawer and routing is concerned, nicely done.
> * Take a look at the comments.
> * Please take a look at your `tailwind.config.js` file, specifically your naming conventions for the custom colours. The naming convention should be kebab-case.
> * Also just a suggestion on the naming of the custom text colours, just name the colour insted of `text-colour`.

As for the `tailwind.config.js` file naming conventions for the colors, I did some research on typical naming conventions, and color names are usually lowercase, not kebabCase. I used the Keyword Naming convention, which is to name a color based on the context in which that color is used. If I have time I plan on adding a dark theme, that is why I specified `primary_blue` instead of `primary_color`. I do see however that a hyphen is more conventional than an underscore, so I will change that.

2024-03-15 08:21 UTC, yanevdw approved these changes
Looks good

2024-03-15 19:07 UTC, Musa-Mabasa commented on src/profilePage/ProfilePage.tsx
> +      <Drawer username={"julianna-venter"} />
You do not have to evaluate the attribute assignment for string literals 🎨

2024-03-15 19:12 UTC, Musa-Mabasa approved these changes
Left one comment about attribute assignment. Either than that, everything looked good.

2024-03-15 19:14 UTC, Musa-Mabasa commented on src/commonComponents/BackgroundAssets.tsx
> +      <div className="w-[18.75rem] h-[9.375rem] border-solid border-12 border-secondary_orange absolute rounded-badge -z-10 left-[6rem] top-[-8rem] rotate-45 flex-0"></div>
I agree, however I think the needed implementation for now is to not scale anything according to the browser.

2024-03-16 21:17 UTC, Hugovs2000 approved these changes
All good

2024-03-19 10:11 UTC, merged