Feature profile query
Julianna-Venter/React-Project-Github pull request #7
Opened 2024-03-25 09:56 UTC by Julianna-Venter

Added all the dynamic data for the profile page.
Note: all console logs for errors and similar scenarios will be handled appropriately in another branch (with some ERROR page, or something similar), as well as "Loading..." with spinners/skeletonUI

2024-03-25 12:31 UTC, yanevdw commented on src/profilePage/ProfilePage.tsx
> +          const newRepos = data.map((repo: RepoItem) => ({
Please move `getProfile` and `getRepos` to a separate file, `api.ts` which you can store in, for example, a `services` directory inside `src`.

2024-03-25 12:54 UTC, yanevdw commented on src/profilePage/QuickStats.tsx
> +  };
Please move this to an `api.ts` file. Just better for separation of concerns.

2024-03-25 12:55 UTC, yanevdw commented on src/profilePage/RepoCard.tsx
> +  };
Please move to `api.ts` or something similar.

2024-03-25 12:55 UTC, yanevdw commented on src/profilePage/RepoCard.tsx
> +  };
This too.

2024-03-25 12:55 UTC, yanevdw commented on src/profilePage/RepoCard.tsx
> +  };
This too.

2024-03-25 12:56 UTC, yanevdw commented on src/profilePage/StatsCarousel.tsx
> +  };
Move to `api.ts` or similar file.

2024-03-25 12:58 UTC, yanevdw requested changes
Overall, really good job. Just move the API calls to a designated file please for better readablity and separation of concerns.

2024-03-25 13:44 UTC, yanevdw approved these changes
Requested changes have been made. Everything looks good to me.

2024-03-25 14:52 UTC, theadley requested changes
Many of the comments I didn't make are just more of the same, so please apply the same logic re TSQ/useEffect and Object.entries and keys not using index across the codebase.

2024-03-25 14:52 UTC, theadley commented on src/Models/calendarHeatmap.ts
> +export let until = currentDate.toISOString().substring(0, 10);
let?

2024-03-25 14:52 UTC, theadley commented on src/Models/calendarHeatmap.ts
>  export let weekLabelAttributes = {
let?

2024-03-25 14:52 UTC, theadley commented on src/ProfilePage/Api/profileApi.ts
> +        sendUpCommits(newCommits);
Please could you explain why you have 2 callback functions that do the same thing?

2024-03-25 14:52 UTC, theadley commented on src/ProfilePage/Api/profileApi.ts
> +      console.error("Error fetching repositories:", error);
Do you have access to a little toast component service or something so you can give the user some feedback?

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +  useEffect(() => {
But why? You have TSQ?

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +    enabled: false,
👀🤔

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +      for (const [language, count] of Object.entries(languages)) {
Isn't the second part of the tuple the index not the count?
Therefore adding the count won't just add one each time 🤔

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +        var oldDateCompare = new Date(formattedPreviousDate);
What year is it that we're using `var`

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +                  <img src={profile?.avatar_url} alt="Profile Avatar" />
You can have a fallback image/initials if profile doesn't exist

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +                          key={index}
👀

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +                    <span>More</span>
What is this for?

2024-03-25 14:52 UTC, theadley commented on src/profilePage/QuickStats.tsx
> +  });
Reruns every renter, no dep array.
Also why useEffect when you have TSQ?

2024-03-25 14:52 UTC, theadley commented on src/profilePage/QuickStats.tsx
> +    enabled: false,
👀

2024-03-25 14:52 UTC, theadley commented on src/profilePage/RepoCard.tsx
> +          <span>{repoInfo.private ? <p>Private</p> : <p>Public</p>}</span>
Why a paragraph inside a span 🤔

2024-03-25 14:52 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +      for (const [language, count] of Object.entries(languages)) {
Or if not, why use Object.entries?

2024-03-25 14:52 UTC, theadley commented on src/profilePage/RepoCard.tsx
> +  }, []);
The confusion I have where you have tanstack query setup for this, but disable it...

2024-03-25 14:52 UTC, theadley commented on src/profilePage/RepoCard.tsx
> +          {Object.entries(languages)
Help me understand why not just map?

2024-03-25 14:52 UTC, theadley commented on src/profilePage/RepoCard.tsx
> +                  key={`${repoInfo.id}_${language}_${index}`}
Index is not part of a valid key

2024-03-25 14:52 UTC, theadley commented on src/routeTree.gen.ts
> +} as any);
🤢

2024-03-25 14:52 UTC, theadley commented on src/routeTree.gen.ts
> +} as any);
I know it's generated, just leave me. Just resolve this haha.

2024-03-25 14:52 UTC, theadley commented on src/userForm/Api/userFormApi.ts
> +      let data: any;
but why tho

2024-03-25 15:04 UTC, tanadendere approved these changes
Well done, I noticed the const vs let thing, thats all. Otherwise it looks good to me

2024-03-25 15:04 UTC, tanadendere commented on src/Models/calendarHeatmap.ts
>  export let weekLabelAttributes = {
I see you are using `let` for some of the attributes and `const` for others... I checked in `ProfilePage.tsx` where you import them, and it seemed you were not changing them there. Will you be updating the ones you are using `let` for?

2024-03-25 15:04 UTC, tanadendere commented on src/Models/interfaces.d.ts
> +  [key: string]: number;
Nice!

2024-03-25 15:04 UTC, tanadendere commented on src/ProfilePage/Api/profileApi.ts
> +        let repos = res.data.length;
I think this should be `const` as well

2024-03-25 15:04 UTC, tanadendere commented on src/profilePage/ProfilePage.tsx
Love the "give me" naming convention in this file 😂🤌🏾

2024-03-26 10:43 UTC, Julianna-Venter commented on src/ProfilePage/Api/profileApi.ts
> +        sendUpCommits(newCommits);
setCommits is used for the dom manipulation within the RepoCard component, sendUpCommits passes them to the parent element ProfilePage so that it can use it for it's own calculations

2024-03-26 10:43 UTC, Julianna-Venter commented on src/ProfilePage/Api/profileApi.ts
> +      console.error("Error fetching repositories:", error);
I'm currently working on these all together with a en error page on another branch

2024-03-26 10:43 UTC, Julianna-Venter commented on src/profilePage/ProfilePage.tsx
> +  useEffect(() => {
Was used during testing initially, but I realise it's quite useless now

2024-03-26 10:43 UTC, Julianna-Venter commented on src/profilePage/ProfilePage.tsx
> +      for (const [language, count] of Object.entries(languages)) {
count is the number of "units" the language has, like points. I'm not sure what unit measurement they use. Maybe just a confusing name. But object.entries provides a "destructuring" of the object in a key/value pair, and I was getting an error trying to use other options like map and forEach, and this was presented as an alternative after googling a bit

2024-03-26 10:43 UTC, Julianna-Venter commented on src/profilePage/ProfilePage.tsx
> +                    <span>More</span>
Unsure of the question, but if you are referring to the  `Less/More` text, this is a key for the commits heatmap indicating what colors indicate how many commits on the color gradient

2024-03-27 08:21 UTC, theadley reviewed
Please check the outstanding comments

2024-03-27 08:21 UTC, theadley commented on src/profilePage/ProfilePage.tsx
> +                    <span>More</span>
Oooooooh. NVM, thought it was like "read more". My bad.

2024-03-27 08:21 UTC, theadley commented on package.json
> +    "uuid": "^9.0.1",
Do you need this now?

2024-03-27 08:21 UTC, theadley commented on src/ProfilePage/Api/profileApi.ts
> +        sendUpCommits(newCommits);
Did you change this now to do both from the caller?

2024-03-29 10:24 UTC, Hugovs2000 approved these changes
Very impressive Julz, crazy amount of work. Well done 👏

2024-03-29 10:39 UTC, merged